services:
  data_collection:
    build:
      context: .
      dockerfile: ./data_collection/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - API_URL=${API_URL}

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - VERSION=${VERSION}
    ports:
      - "${API_DOCKER_PORT}:8000"

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ${ENVIRONMENT}_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_DOCKER_PORT}:80"
    depends_on:
      - db
    volumes:
      - ${ENVIRONMENT}_pgadmin_data:/var/lib/pgadmin

volumes:
  ${ENVIRONMENT}_postgres_data:
    external: true
  ${ENVIRONMENT}_pgadmin_data:
    external: true
